name: 'formula_one_aws_analytics'
version: '1.0.0'
config-version: 2

profile: 'formula_one_aws_analytics'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  formula_one_aws_analytics:
    +materialized: view
